/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.0
  Forc version: 0.68.2
  Fuel-Core version: 0.43.1
*/

import { ContractFactory as __ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions } from "fuels";

import { PartsNft } from "./PartsNft";

const bytecode = decompressBytecode("H4sIAAAAAAAAA6VTMWgUURCdPU9cLWTkrvoiLnIWBpJscokcpNnPZtm7nMf9MoWLvxEsAoZDDkGElDaCEdSUKS3/dZZXpkxpeaUBA2mEkxTnm709UFkrF5bZ/2bem8fMX3UR0guiKuXPlXdFPM5mY49nM8mR+m7okLyTQUQ7T87JU5ElxDBLXZjFzhu0yb+tG8S6Lvg6sHV1RhRMm7R7OamYy0kVOm/B7yBPBX8NdWvQoJyfNCLW1Qh4E3izhP9axafC20B+w6RuH983TeymVrNv0pGxCfkmHhloLmUJo5Zb8p3rt+sHnNQPgC0BayGugLOfdd2K6Ttre+Dq0M+1YsdWh4y8gyaLxu984CQ4eu2iHtEd5TF1QYGDn59f5vzY3ZNepusMPN8wOlj0Ca0OpM+ChzOj34XHCY9NdxTZDnBEeMRs2B9s01XE69B+YxN47LvP8M7qLPx7XrHMC/kvtsdl+S3VP6Waro5rPdkJ0fAR3YWnr+KpZP7bxfw3UfNNfJbUbBU1q6g5+YfOnaJmGbPfxGxWMd/lB7pxaxhRBXfk1UN4ET/38X4guvbRn99BFR+TSic0BCY7rXWCaNimSqZJ7qn3eB5J/cD7k+kIvE+o3Zn+qXNI1FpoYScsM7bn2EOM/WH3shfg2FHgy/0WvffC+U9NRNHL/ZXppfD+7One3vP5T4jHm/4Cm2ollaADAAA=");

export class PartsNftFactory extends __ContractFactory<PartsNft> {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      PartsNft.abi,
      accountOrProvider,
      PartsNft.storageSlots
    );
  }

  static deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ) {
    const factory = new PartsNftFactory(wallet);
    return factory.deploy(options);
  }
}
